name: tweetbot

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  tweetbot-post:
    runs-on: macOS-latest
    env:
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      MEANINGCLOUD_TOKEN: ${{ secrets.MEANINGCLOUD_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    with:
        python-version: '3.x'
    - run: script.py 
    - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
