name: mergebot

on:
  schedule:
    - cron: '00 21 * * *'

jobs:
  mergebot-post:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: Rscript -e 'install.packages(c("httr", "jsonlite"), dependencies = TRUE)'
      - name: Merge files
        run: Rscript merge_files.R
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
